manifest:
  remotes:
    - name: Akadimia-Robot
      url-base: https://github.com/Akadimia-Robot
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: Akadimia-Robot

  projects:
    - name: zephyr
      repo-path: zephyr
      revision: v4.0.0
      import:
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - hal_stm32
          - babblesim
          - mcuboot
          - fatfs
          - segger
          - lvgl
    - name: renode
      repo-path: renode
      revision: 03756cb5a3112fb94aeffef227ddec48db531cad
      path: tools/renode
